#!/bin/bash

if [ -z "${CC}" ];
then
	CC=gcc
fi

${CC} -nostdinc -std=gnu11 -I`dirname ${0}`/include -m16 -O3 -c ${@} &&\
for file in ${@};
do
	objfile=${file%.*}.o
	if [ -f ${objfile} ];
	then
		objcopy -R.eh_frame ${objfile} ${objfile}
		objcopy -R.comment ${objfile} ${objfile}
	fi
done

exit ${?}
