#!/bin/sh

CC=${CC-gcc}
CFLAGS=${CFLAGS--nostdinc -std=gnu11 -I`pwd`/include -m16 -O3}
OBJCOPY=${OBJCOPY-objcopy}

${CC} ${CFLAGS} -c ${@} &&\
for file in ${@};
do
	obj=${file%.*}.o
	${OBJCOPY} -R.eh_frame -R.comment ${obj} ${obj};
done

exit ${?}
