#ifndef _MLIBC_BIOS_H_INCLUDED_
#define _MLIBC_BIOS_H_INCLUDED_ 1

#include <mlibc.h>

/* BIOS video attribute macros */
#define BIOS_VIDEO_ATTRIB(page, color) (((page) << 0x08) | (color))
#define BIOS_VIDEO_ATTRIB_DEFAULT BIOS_VIDEO_ATTRIB(BIOS_VIDEO_PAGE_CURRENT, BIOS_VIDEO_COLOR_DEFAULT)

/* BIOS video position macros */
#define BIOS_VIDEO_POS(x, y) (((y) << 0x08) | (x))
#define BIOS_VIDEO_SCREEN_SIZE BIOS_VIDEO_POS(BIOS_VIDEO_POS_ROWS, BIOS_VIDEO_POS_COLS)
#define BIOS_VIDEO_ROWS 0x50
#define BIOS_VIDEO_COLS 0x19

/* BIOS video page macros */
#define BIOS_VIDEO_PAGE_CURRENT 0x00

/* BIOS video color macros */
#define BIOS_VIDEO_COLOR(fore, back, shine) (((shine & 0x01) << 0x07) | (((back) & 0x07) << 0x04)) | (fore))
#define BIOS_VIDEO_COLOR_DEFAULT BIOS_VIDEO_COLOR(BIOS_VIDEO_LIGHT_GRAY, BIOS_VIDEO_BLACK, BIOS_VIDEO_NO_SHINE)
#define BIOS_VIDEO_BLACK 0x00
#define BIOS_VIDEO_BLUE 0x01
#define BIOS_VIDEO_GREEN 0x02
#define BIOS_VIDEO_CYAN 0x03
#define BIOS_VIDEO_RED 0x04
#define BIOS_VIDEO_MAGNETA 0x05
#define BIOS_VIDEO_BROWN 0x06
#define BIOS_VIDEO_LIGHT_GRAY 0x07
#define BIOS_VIDEO_DARK_GRAY 0x08
#define BIOS_VIDEO_LIGHT_BLUE 0x09
#define BIOS_VIDEO_LIGHT_GREEN 0x0A
#define BIOS_VIDEO_LIGHT_CYAN 0x0B
#define BIOS_VIDEO_LIGHT_RED 0x0C
#define BIOS_VIDEO_LIGHT_MAGNETA 0x0D
#define BIOS_VIDEO_YELLOW 0x0E
#define BIOS_VIDEO_WHITE 0x0F
#define BIOS_VIDEO_NO_SHINE 0x00
#define BIOS_VIDEO_SHINE 0x01

#endif /* _MLIBC_BIOS_H_INCLUDED_ */
