#ifndef _MLIBC_BIOS_H_INCLUDED_
#define _MLIBC_BIOS_H_INCLUDED_ 1

#define BIOS_VIDEO_POS(x, y) ((y << 0x08) | (x))
#define BIOS_VIDEO_POS_DEFAULT BIOS_VIDEO_POS(BIOS_VIDEO_ROWS, BIOS_VIDEO_COLS)
#define BIOS_VIDEO_ROWS 0x50
#define BIOS_VIDEO_COLS 0x19
#define BIOS_VIDEO_ATTRIB(page, color) (((page) << 0x08) | (color))
#define BIOS_VIDEO_ATTRIB_DEFAULT BIOS_VIDEO_ATTRIB(BIOS_PAGE_CURRENT, BIOS_COLOR_DEFAULT)
#define BIOS_PAGE_CURRENT 0x00 
#define BIOS_COLOR(fore, back) (((back) << 0x04) | (fore))
#define BIOS_COLOR_DEFAULT BIOS_COLOR(BIOS_COLOR_LIGHT_GRAY, BIOS_COLOR_BLACK)
#define BIOS_COLOR_BLACK 0x00
#define BIOS_COLOR_BLUE 0x01
#define BIOS_COLOR_GREEN 0x02
#define BIOS_COLOR_CYAN 0x03
#define BIOS_COLOR_RED 0x04
#define BIOS_COLOR_MAGNETA 0x05
#define BIOS_COLOR_BROWN 0x06
#define BIOS_COLOR_LIGHT_GRAY 0x07
#define BIOS_COLOR_DARK_GRAY 0x08
#define BIOS_COLOR_LIGHT_BLUE 0x09
#define BIOS_COLOR_LIGHT_GREEN 0x0A
#define BIOS_COLOR_LIGHT_CYAN 0x0B
#define BIOS_COLOR_LIGHT_RED 0x0C
#define BIOS_COLOR_LIGHT_MAGNETA 0x0D
#define BIOS_COLOR_YELLOW 0x0E
#define BIOS_COLOR_WHITE 0x0F

#endif /* _MLIBC_BIOS_H_INCLUDED_ */
